name: update WebGlBuild
on: push
jobs:
  copy-folder:
    runs-on: ubuntu-latest    
    steps: 
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'vindex-3D-unity/WebGlBuild/'
          destination-username: 'sm-vindex'
          destination-repository: 'vindex'
          destination-branch: 'master'
          destination-directory: 'vindex/public/assets/'
          commit-email: 'zzpdavid2l@gmail.com'
          commit-message: 'Update Unity build'
